name: quran_app_mvp
description: MVP Quran app in Flutter
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.42
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/quran_sample.json
